package coach.interfaces.customer;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import coach.dao.dbConnection;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;

public class customerPage extends JPanel implements ActionListener {

    // TODO: 1/2/2022
    String customer_id = "10";
    String tableData[][] = new String[25][20];

    DefaultTableModel model;

    //construct components
    JFrame frame = new JFrame("Customer Profile");
    String[] comp1Items = {"Male", "Female"};
    JComboBox genderBox = new JComboBox(comp1Items);

    JLabel firstName = new JLabel("First name:");
    JLabel surname = new JLabel("Last name:");
    JLabel jcomp3 = new JLabel("Gender:");
    JLabel email = new JLabel("Email:");
    JLabel address = new JLabel("Address:");
    JLabel jcomp6 = new JLabel("DOB:");
    JLabel phoneNo = new JLabel("Phone Number:");
    JLabel firstname_label;
    JButton editDetails = new JButton("Edit Details");
    JButton book_route = new JButton("Book Route");
    JButton deleteRoute = new JButton("Delete Route");
    JTable table = new JTable();
    JScrollPane tableWithScrolBox = new JScrollPane(table);
    JLabel lastname_label;

    JLabel dob_label;
    JLabel mail_label;
    JLabel phone_label;
    JLabel addr_label;

    public customerPage() {
        createWindow();
        populateData();
        createTable();
        setJlabelParams();
        setLocationAndSize();
        addComponentsToFrame();
        setVisibleWindow();
        actionEvent();
    }

    private void setVisibleWindow() {
        frame.setVisible(true);
    }

    private void createWindow() {
        frame.setPreferredSize(new Dimension(850, 520));
        frame.setLayout(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
    }

    public void createTable() {
        Object[] columns = {"Route Id", "Origin", "originCity", "Destination", "destinationCity", "Departure", "time", "Price", "Seates", "RemainSeats"};
        model = new DefaultTableModel(tableData, columns);
        model.setColumnIdentifiers(columns);
        table.setModel(model);
//        table.setBackground(Color.CYAN.brighter());
//        table.setForeground(Color.black);
//        Font font = new Font("", 1, 18);
//        table.setFont(font);
        table.setRowHeight(30);
    }


    public void setLocationAndSize() {
        firstName.setBounds(45, 80, 100, 25);
        surname.setBounds(45, 115, 100, 25);
        jcomp3.setBounds(45, 160, 100, 25);
        email.setBounds(325, 80, 150, 25);
        address.setBounds(320, 155, 150, 25);
        jcomp6.setBounds(45, 200, 100, 25);
        phoneNo.setBounds(320, 115, 100, 25);
        firstname_label.setBounds(130, 80, 100, 25);
        editDetails.setBounds(345, 235, 120, 25);
        book_route.setBounds(530, 290, 150, 25);
        deleteRoute.setBounds(700, 290, 115, 25);
        tableWithScrolBox.setBounds(10, 330, 815, 140);
        lastname_label.setBounds(130, 115, 160, 25);
        genderBox.setBounds(130, 160, 100, 25);
        dob_label.setBounds(130, 200, 100, 25);
        mail_label.setBounds(430, 80, 150, 25);
        phone_label.setBounds(430, 115, 100, 25);
        addr_label.setBounds(430, 155, 300, 25);
    }

    public void addComponentsToFrame() {
        frame.add(firstName);
        frame.add(surname);
        frame.add(jcomp3);
        frame.add(email);
        frame.add(address);
        frame.add(jcomp6);
        frame.add(phoneNo);
        frame.add(firstname_label);
        frame.add(editDetails);
        frame.add(book_route);
        frame.add(deleteRoute);
        frame.add(tableWithScrolBox);
        frame.add(lastname_label);
        frame.add(genderBox);
        frame.add(dob_label);
        frame.add(mail_label);
        frame.add(phone_label);
        frame.add(addr_label);
    }

    public void actionEvent() {
        editDetails.addActionListener(this);
        book_route.addActionListener(this);
        deleteRoute.addActionListener(this);
    }

    public void setJlabelParams() {
        ResultSet resultSet = null;
        try {
            Connection conn = dbConnection.getInstance().getConnection();
            PreparedStatement preparedStatement = conn.prepareStatement("SELECT * from busbook.customers where CustomerId= ? ;");
            preparedStatement.setString(1, customer_id);
            resultSet = preparedStatement.executeQuery();
            int i = 0;
            while (resultSet.next()) {
                firstname_label = new JLabel(String.valueOf(resultSet.getString("FirstName")));
                lastname_label = new JLabel(String.valueOf(resultSet.getString("Lastname")));
                mail_label = new JLabel(String.valueOf(resultSet.getString("Email")));
                dob_label = new JLabel(String.valueOf(resultSet.getString("DOB")));
                genderBox.setName(String.valueOf(resultSet.getString("Gender")));
                phone_label = new JLabel(String.valueOf(resultSet.getString("PhoneNumber")));
                addr_label = new JLabel(String.valueOf(resultSet.getString("Address")));
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    private void populateData() {
        ResultSet resultSet = null;
        try {
            Connection conn = dbConnection.getInstance().getConnection();
            String sql = "SELECT * from busbook.routes, busbook.bookedroutes where bookedroutes.routeId = routes.routeId and customerId =?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, customer_id);
            resultSet = preparedStatement.executeQuery();

            int i = 0;
            while (resultSet.next()) {
                String routeId = resultSet.getString("routeId");
                String origin = resultSet.getString("origin");
                String originCity = resultSet.getString("originCity");
                String destination = resultSet.getString("destination");
                String destinationCity = resultSet.getString("destinationCity");
                Date departure = resultSet.getDate("departure");
                Time time = resultSet.getTime("time");
                Double price = resultSet.getDouble("price");
                Integer seats = resultSet.getInt("seats");
                Integer remainSeats = resultSet.getInt("remainSeats");
                tableData[i][0] = String.valueOf(routeId);
                tableData[i][1] = String.valueOf(origin);
                tableData[i][2] = String.valueOf(originCity);
                tableData[i][3] = String.valueOf(destination);
                tableData[i][4] = String.valueOf(destinationCity);
                tableData[i][5] = String.valueOf(departure);
                tableData[i][6] = String.valueOf(time);
                tableData[i][7] = String.valueOf(price);
                tableData[i][8] = String.valueOf(seats);
                tableData[i][9] = String.valueOf(remainSeats);
                i++;

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    @Override
    public void actionPerformed(ActionEvent e) {
            if (e.getSource() == editDetails){
                    new CustomerRegistrationUpdateForm(customer_id);
            }
            if ((e.getSource() == deleteRoute)){
                int column = 0;
                int row = table.getSelectedRow();
                String value = table.getModel().getValueAt(row, column).toString();

                ResultSet resultSet = null;
                Statement statement = null;
                try {
                    Connection conn = dbConnection.getInstance().getConnection();
                    PreparedStatement preparedStatement = conn
                            .prepareStatement("delete from busbook.bookedroutes where routeId= ? ; ");
                    preparedStatement.setString(1, value);
                    preparedStatement.executeUpdate();
//                preparedStatement.execute();
                    model.removeRow(row);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            if (e.getSource() == book_route){
                new bookRoutesCustomer(customer_id);
            }
    }

    public static void main(String[] args) {
        new customerPage();
    }

}
