package coach.interfaces;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class addRouteEmp extends JPanel implements ActionListener {
    String[] jcomp1Items = {"Item 1", "Item 2", "Item 3"};
    String[] jcomp3Items = {"Item 1", "Item 2", "Item 3"};
    String[] jcomp24Items = {"Item 1", "Item 2", "Item 3"};
    String[] jcomp25Items = {"Item 1", "Item 2", "Item 3"};
    String[] jcomp26Items = {"Item 1", "Item 2", "Item 3"};

    JFrame frame = new JFrame ("Add Route Employee");

    JComboBox jcomp1 = new JComboBox (jcomp1Items);
    JLabel jcomp2 = new JLabel ("Origin");
    JComboBox jcomp3 = new JComboBox (jcomp3Items);
    JLabel jcomp4 = new JLabel ("Departure");
    JTextField jcomp5 = new JTextField (5);
    JLabel jcomp6 = new JLabel ("City");
    JTextField jcomp7 = new JTextField (5);
    JLabel jcomp8 = new JLabel ("City");
    JTextField jcomp9 = new JTextField (5);
    JLabel jcomp10 = new JLabel ("Route ID");
    JTextField jcomp11 = new JTextField (5);
    JLabel jcomp12 = new JLabel ("Price");
    JLabel jcomp13 = new JLabel ("Seats");
    JCheckBox jcomp14 = new JCheckBox ("Sun");
    JCheckBox jcomp15 = new JCheckBox ("Mon");
    JTextField jcomp16 = new JTextField (5);
    JCheckBox jcomp17 = new JCheckBox ("Fri");
    JCheckBox jcomp18 = new JCheckBox ("Sat");
    JCheckBox jcomp19 = new JCheckBox ("Thr");
    JCheckBox jcomp20 = new JCheckBox ("Tue");
    JCheckBox jcomp21 = new JCheckBox ("Wed");
    JButton jcomp22 = new JButton ("Add Route");
    JTextField jcomp23 = new JTextField (5);
    JComboBox jcomp24 = new JComboBox (jcomp24Items);
    JComboBox jcomp25 = new JComboBox (jcomp25Items);
    JComboBox jcomp26 = new JComboBox (jcomp26Items);
    JTextField jcomp27 = new JTextField (5);
    JLabel jcomp28 = new JLabel ("Year");
    JLabel jcomp29 = new JLabel ("Date");
    JLabel jcomp30 = new JLabel ("Month");
    JLabel jcomp31 = new JLabel ("Hour");
    JLabel jcomp32 = new JLabel ("Min");


    public addRouteEmp() {
        createWindow();
        setLocationAndSize();
        addComponentsToFrame();
        actionEvent();
    }

    public void createWindow(){
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.setPreferredSize (new Dimension (760, 380));
        frame.setLayout (null);
        frame.pack();
        frame.setVisible (true);
    }


    public void setLocationAndSize(){
        jcomp1.setBounds (25, 35, 150, 25);
        jcomp2.setBounds (25, 10, 100, 25);
        jcomp3.setBounds (405, 35, 150, 25);
        jcomp4.setBounds (405, 10, 100, 25);
        jcomp5.setBounds (180, 35, 150, 25);
        jcomp6.setBounds (180, 10, 100, 25);
        jcomp7.setBounds (560, 35, 150, 25);
        jcomp8.setBounds (560, 10, 100, 25);
        jcomp9.setBounds (35, 125, 150, 25);
        jcomp10.setBounds (35, 100, 100, 25);
        jcomp11.setBounds (35, 180, 100, 25);
        jcomp12.setBounds (35, 155, 100, 25);
        jcomp13.setBounds (35, 210, 100, 25);
        jcomp14.setBounds (230, 120, 50, 25);
        jcomp15.setBounds (230, 145, 50, 25);
        jcomp16.setBounds (35, 235, 100, 25);
        jcomp17.setBounds (305, 145, 55, 25);
        jcomp18.setBounds (305, 170, 55, 25);
        jcomp19.setBounds (305, 120, 55, 25);
        jcomp20.setBounds (230, 170, 55, 25);
        jcomp21.setBounds (230, 195, 65, 25);
        jcomp22.setBounds (320, 305, 100, 25);
        jcomp23.setBounds (435, 130, 80, 25);
        jcomp24.setBounds (520, 130, 100, 25);
        jcomp25.setBounds (625, 130, 100, 25);
        jcomp26.setBounds (475, 195, 100, 25);
        jcomp27.setBounds (580, 195, 80, 25);
        jcomp28.setBounds (435, 105, 40, 25);
        jcomp29.setBounds (625, 105, 40, 25);
        jcomp30.setBounds (520, 105, 45, 25);
        jcomp31.setBounds (475, 170, 35, 25);
        jcomp32.setBounds (580, 170, 30, 25);
    }

    public void addComponentsToFrame() {
        frame.add (jcomp1);
        frame.add (jcomp2);
        frame.add (jcomp3);
        frame.add (jcomp4);
        frame.add (jcomp5);
        frame.add (jcomp6);
        frame.add (jcomp7);
        frame.add (jcomp8);
        frame.add (jcomp9);
        frame.add (jcomp10);
        frame.add (jcomp11);
        frame.add (jcomp12);
        frame.add (jcomp13);
        frame.add (jcomp14);
        frame.add (jcomp15);
        frame.add (jcomp16);
        frame.add (jcomp17);
        frame.add (jcomp18);
        frame.add (jcomp19);
        frame.add (jcomp20);
        frame.add (jcomp21);
        frame.add (jcomp22);
        frame.add (jcomp23);
        frame.add (jcomp24);
        frame.add (jcomp25);
        frame.add (jcomp26);
        frame.add (jcomp27);
        frame. add (jcomp28);
        frame.add (jcomp29);
        frame.add (jcomp30);
        frame.add (jcomp31);
        frame.add (jcomp32);

    }

    public void actionEvent() {
        jcomp22.addActionListener(this);
    }


    @Override
    public void actionPerformed(ActionEvent e) {

    }

    public static void main (String[] args) {
        new addRouteEmp();
    }

}
