package coach.interfaces;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class bookRoutesCustomer extends JPanel implements ActionListener {

    String[] sourceItems = {"Item 1", "Item 2", "Item 3"};
    String[] destinationItems = {"Item 1", "Item 2", "Item 3"};

    JFrame frame = new JFrame ("Book Routes");
    JComboBox source = new JComboBox (sourceItems);
    JComboBox destination = new JComboBox (destinationItems);
    JTable table = new JTable ();
    JScrollPane tableWithScrolBox = new JScrollPane(table);
    JButton searchBtn = new JButton ("Search");
    JButton bookRouteBtn = new JButton ("Book Selected Route");


    public bookRoutesCustomer() {
        createWindow();
        createTable();
        setLocationAndSize();
        addComponentsToFrame();
        setVisibleWindow();
        actionEvent();
    }

    private void setVisibleWindow(){frame.setVisible(true);}

    public void createWindow() {
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.setPreferredSize (new Dimension (745, 350));
        frame.setLayout (null);
        frame.pack();
    }

    public void createTable() {
        Object[] columns = { "Route Id", "Origin", "Destination", "Departure" };
        final DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table.setModel(model);
        table.setBackground(Color.CYAN.brighter());
        table.setForeground(Color.black);
        Font font = new Font("", 1, 18);
        table.setFont(font);
        table.setRowHeight(30);
    }

    public void setLocationAndSize() {
        tableWithScrolBox.setBounds (20, 130, 690, 155);
        source.setBounds (20, 95, 145, 25);
        destination.setBounds (180, 95, 145, 25);
        searchBtn.setBounds (340, 95, 100, 25);
        bookRouteBtn.setBounds (540, 95, 170, 25);
    }

    public void addComponentsToFrame() {
        frame.add (tableWithScrolBox);
        frame.add (source);
        frame.add (destination);
        frame.add (searchBtn);
        frame.add (bookRouteBtn);
    }

    public void actionEvent() {
        searchBtn.addActionListener(this);
        bookRouteBtn.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {

    }


    public static void main (String[] args) {
        new bookRoutesCustomer();
    }
}
