package coach.interfaces;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class customerPage extends JPanel implements ActionListener {

    //construct components
    JFrame frame = new JFrame ("My Profile");

    JLabel firstName = new JLabel ("First name:");
    JLabel surname = new JLabel ("Surname:");
    JLabel jcomp3 = new JLabel ("Gender:");
    JLabel email = new JLabel ("Email:");
    JLabel address = new JLabel ("Address:");
    JLabel jcomp6 = new JLabel ("DOB:");
    JLabel phoneNo = new JLabel ("Phone Number:");
    JTextField jcomp8 = new JTextField ("newLabel1");
    JButton editDetails = new JButton ("Edit Details");
    JButton exploreRoutes = new JButton ("Explore Routes");
    JButton deleteRoute = new JButton ("Delete Route");
    JTable table = new JTable ();
    JScrollPane tableWithScrolBox = new JScrollPane(table);
    JTextField jcomp13 = new JTextField ("newLabel2");

    String[] jcomp1Items = {"Item 1", "Item 2", "Item 3"};
    JComboBox genderBox = new JComboBox (jcomp1Items);

    JTextField jcomp15 = new JTextField ("newLabel4");
    JTextField jcomp16 = new JTextField ("newLabel5");
    JTextField jcomp17 = new JTextField ("newLabel6");
    JTextField jcomp18 = new JTextField ("newLabel7");

    public customerPage() {
        createWindow();
        createTable();
        setLocationAndSize();
        addComponentsToFrame();
        actionEvent();

    }

    private void createWindow() {
        frame.setPreferredSize (new Dimension (850, 520));
        frame.setLayout (null);
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible (true);
    }

    public void createTable() {
        Object[] columns = { "Route Id", "Origin", "Destination", "Departure", "Price", "Seates", "Date" };
        final DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table.setModel(model);
        table.setBackground(Color.CYAN.brighter());
        table.setForeground(Color.black);
        Font font = new Font("", 1, 18);
        table.setFont(font);
        table.setRowHeight(30);
    }

    public void setLocationAndSize() {
        firstName.setBounds(45, 80, 100, 25);
        surname.setBounds(45, 115, 100, 25);
        jcomp3.setBounds(45, 160, 100, 25);
        email.setBounds(325, 80, 100, 25);
        address.setBounds(320, 155, 100, 25);
        jcomp6.setBounds(45, 200, 100, 25);
        phoneNo.setBounds(320, 115, 100, 25);
        jcomp8.setBounds(130, 80, 100, 25);
        editDetails.setBounds(345, 235, 100, 25);
        exploreRoutes.setBounds(530, 290, 150, 25);
        deleteRoute.setBounds(700, 290, 115, 25);
        tableWithScrolBox.setBounds(10, 330, 815, 140);
        jcomp13.setBounds(130, 115, 160, 25);
        genderBox.setBounds(130, 160, 100, 25);
        jcomp15.setBounds(130, 200, 100, 25);
        jcomp16.setBounds(430, 80, 100, 25);
        jcomp17.setBounds(430, 115, 100, 25);
        jcomp18.setBounds(430, 155, 100, 25);
    }

    public void addComponentsToFrame() {
        frame.add(firstName);
        frame.add(surname);
        frame.add(jcomp3);
        frame.add(email);
        frame.add(address);
        frame.add(jcomp6);
        frame.add(phoneNo);
        frame.add(jcomp8);
        frame.add(editDetails);
        frame.add(exploreRoutes);
        frame.add(deleteRoute);
        frame.add(tableWithScrolBox);
        frame.add(jcomp13);
        frame.add(genderBox);
        frame.add(jcomp15);
        frame.add(jcomp16);
        frame.add(jcomp17);
        frame.add(jcomp18);
    }

    public void actionEvent()
    {
        editDetails.addActionListener(this);
        exploreRoutes.addActionListener(this);
        deleteRoute.addActionListener(this);
    }


    @Override
    public void actionPerformed(ActionEvent e) {

    }

    public static void main (String[] args) {
        new customerPage();
    }

}
