package coach.interfaces;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class customerPage extends JPanel implements ActionListener {

    //construct components
    JFrame frame = new JFrame ("Customer Profile");
    String[] comp1Items = {"Male", "Female"};
    JComboBox genderBox = new JComboBox (comp1Items);

    JLabel firstName = new JLabel ("First name:");
    JLabel surname = new JLabel ("Surname:");
    JLabel jcomp3 = new JLabel ("Gender:");
    JLabel email = new JLabel ("Email:");
    JLabel address = new JLabel ("Address:");
    JLabel jcomp6 = new JLabel ("DOB:");
    JLabel phoneNo = new JLabel ("Phone Number:");
    JLabel jcomp8 = new JLabel ("newLabel1");
    JButton editDetails = new JButton ("Edit Details");
    JButton addRoute = new JButton ("Add Route");
    JButton deleteRoute = new JButton ("Delete Route");
    JTable table = new JTable ();
    JScrollPane tableWithScrolBox = new JScrollPane(table);
    JLabel jcomp13 = new JLabel ("newLabel2");

    JLabel jcomp15 = new JLabel ("newLabel4");
    JLabel jcomp16 = new JLabel ("newLabel5");
    JLabel jcomp17 = new JLabel ("newLabel6");
    JLabel jcomp18 = new JLabel ("newLabel7");


    JRadioButton sunToggle = new JRadioButton ("sun");
    JRadioButton monToggle = new JRadioButton ("mon");
    JRadioButton tueToggle = new JRadioButton ("tue");
    JRadioButton wedToggle = new JRadioButton ("wed");
    JRadioButton thrToggle = new JRadioButton ("thr");
    JRadioButton friToggle = new JRadioButton ("fri");
    JRadioButton satToggle = new JRadioButton ("sat");

    public customerPage() {
        createWindow();
        createTable();
        setLocationAndSize();
        addComponentsToFrame();
        actionEvent();

    }

    private void createWindow() {
        frame.setPreferredSize (new Dimension (850, 520));
        frame.setLayout (null);
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible (true);
    }

    public void createTable() {
        Object[] columns = { "Route Id", "Origin", "Destination", "Departure", "Price", "Seates", "Date" };
        final DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        table.setModel(model);
        table.setBackground(Color.CYAN.brighter());
        table.setForeground(Color.black);
        Font font = new Font("", 1, 18);
        table.setFont(font);
        table.setRowHeight(30);
    }

    public void setLocationAndSize() {
        firstName.setBounds(45, 80, 100, 25);
        surname.setBounds(45, 115, 100, 25);
        jcomp3.setBounds(45, 160, 100, 25);
        email.setBounds(325, 80, 100, 25);
        address.setBounds(320, 155, 100, 25);
        jcomp6.setBounds(45, 200, 100, 25);
        phoneNo.setBounds(320, 115, 100, 25);
        jcomp8.setBounds(130, 80, 100, 25);
        editDetails.setBounds(345, 235, 120, 25);
        addRoute.setBounds(530, 290, 150, 25);
        deleteRoute.setBounds(700, 290, 115, 25);
        tableWithScrolBox.setBounds(10, 330, 815, 140);
        jcomp13.setBounds(130, 115, 160, 25);
        genderBox.setBounds(130, 160, 100, 25);
        jcomp15.setBounds(130, 200, 100, 25);
        jcomp16.setBounds(430, 80, 100, 25);
        jcomp17.setBounds(430, 115, 100, 25);
        jcomp18.setBounds(430, 155, 100, 25);

        sunToggle.setBounds (50, 291, 60, 25);
        monToggle.setBounds (110, 291, 60, 25);
        tueToggle.setBounds (170, 291, 60, 25);
        wedToggle.setBounds (290, 291, 60, 25);
        thrToggle.setBounds (350, 291, 60, 25);
        friToggle.setBounds (410, 291, 100, 25);
        satToggle.setBounds (230, 291, 60, 25);
    }

    public void addComponentsToFrame() {
        frame.add(firstName);
        frame.add(surname);
        frame.add(jcomp3);
        frame.add(email);
        frame.add(address);
        frame.add(jcomp6);
        frame.add(phoneNo);
        frame.add(jcomp8);
        frame.add(editDetails);
        frame.add(addRoute);
        frame.add(deleteRoute);
        frame.add(tableWithScrolBox);
        frame.add(jcomp13);
        frame.add(genderBox);
        frame.add(jcomp15);
        frame.add(jcomp16);
        frame.add(jcomp17);
        frame.add(jcomp18);

        frame.add (sunToggle);
        frame.add (monToggle);
        frame.add (tueToggle);
        frame.add (wedToggle);
        frame.add (thrToggle);
        frame.add (friToggle);
        frame.add (satToggle);
    }

    public void actionEvent()
    {
        editDetails.addActionListener(this);
        addRoute.addActionListener(this);
        deleteRoute.addActionListener(this);
    }


    @Override
    public void actionPerformed(ActionEvent e) {

    }

    public static void main (String[] args) {
        new employeePage();
    }

}
